# Generated by Django 4.2.6 on 2023-10-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0002_studentdetails_groups_studentdetails_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='student_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
