# Generated by Django 4.2.6 on 2023-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentdetails_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
